### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Mrmitrofan** [asish1346/NotPixelBot#3]
Painted on (x=264, y=68) with color #FFB470| Reward: None 🟨| Charges: 23

**Comment by asish1346** [comment]
Fixing This

**Comment by asish1346** [comment]
@Mrmitrofan This Issue is fixed just update the bot

**Comment by Mrmitrofan** [comment]
> @MrmitrofanЭта проблема исправлена, просто обновите бота.

Skipping .env copying
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\NotPixelBot-master\main.py", line 5, in <module>
    from bot.utils.launcher import process
  File "C:\Users\Admin\Desktop\NotPixelBot-master\bot\utils\launcher.py", line 10, in <module>
    from bot.core.notpxbot import run_notpxbot
  File "C:\Users\Admin\Desktop\NotPixelBot-master\bot\core\notpxbot.py", line 14, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
done

**Comment by asish1346** [comment]
Just install the aiofiles

pip install aiofiles
